name: projectgeprekdiba
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0-334.4.beta

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/admin_profile.jpg
    - assets/admin_profile.png
    - assets/menu1.jpg
    - assets/menu2.jpg
    - assets/menu3.jpg
    - assets/menu4.jpg
    - assets/menu5.jpg
    - assets/sila.jpg
    - assets/indah.jpg
    - assets/wiwin.jpg
    - assets/default.jpg
